-- ITEMTREE — production schema mirror.
-- H2 in MODE=Oracle accepts these types and the recursive CTE / sequence syntax.
CREATE TABLE ITEMTREE (
    ITEMTREEID     NUMBER(10) PRIMARY KEY,
    PARENTID       NUMBER(10) NOT NULL,
    NAME           VARCHAR2(70) NOT NULL,
    TYPE           VARCHAR2(30) NOT NULL,
    XML            CLOB,
    LASTUPDATEUSER VARCHAR2(20),
    LASTUPDATE     DATE,
    JSON           CLOB
);

CREATE INDEX IDX_ITEMTREE_PARENTID  ON ITEMTREE(PARENTID);
CREATE INDEX IDX_ITEMTREE_LASTUPDATE ON ITEMTREE(LASTUPDATE);

CREATE SEQUENCE ITEMTREE_ID_SQN START WITH 100000 INCREMENT BY 1;
