package com.myxcomp.ice.xtree.service.exception;

public enum ErrorCode {
    PARENT_NOT_FOUND,
    PARENT_NOT_FOLDER,
    MOVE_INTO_DESCENDANT,
    NEW_PARENT_NOT_FOUND,
    NEW_PARENT_NOT_FOLDER,
    TYPE_CANNOT_HAVE_DATA,
    DATA_REQUIRED,
    FOLDER_CANNOT_HAVE_DATA,
    ITEM_NOT_FOUND,
    HOME_FOLDER_NOT_FOUND,
    INVALID_SEARCH_PARAMS,
    DATA_NOT_SERIALISABLE,
    CANNOT_COPY_ROOT,
    DESTINATION_NOT_FOUND,
    DESTINATION_NOT_FOLDER,
    DESTINATION_NOT_IN_USER_FOLDER,
    COPY_INTO_DESCENDANT,
    COPY_TOO_LARGE
}
